import { useIntersectionObserver } from '../hooks/useIntersectionObserver'

export default function About() {
  const sectionRef = useIntersectionObserver()

    return (
        <section
              id="about"
                    ref={sectionRef as React.RefObject<HTMLElement>}
                          className="relative py-32 px-6 overflow-hidden"
                              >
                                    <div className="absolute top-0 right-0 w-96 h-96 pointer-events-none">
                                            <div
                                                      className="w-full h-full"
                                                                style={{
                                                                            background:
                                                                                          'radial-gradient(circle, rgba(56,189,248,0.04) 0%, transparent 70%)',
                                                                                                    }}
                                                                                                            />
                                                                                                                  </div>

                                                                                                                        <div className="max-w-4xl mx-auto">
                                                                                                                                <div className="space-y-12">

                                                                                                                                          <div className="section-reveal">
                                                                                                                                                      <p className="text-[#38BDF8] text-xs font-light tracking-[0.5em] uppercase mb-4">
                                                                                                                                                                    About
                                                                                                                                                                                </p>

                                                                                                                                                                                            <h2
                                                                                                                                                                                                          className="text-white font-light mb-8"
                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                        fontSize: 'clamp(2rem, 4vw, 3rem)',
                                                                                                                                                                                                                                                        fontFamily: 'Inter',
                                                                                                                                                                                                                                                                        fontWeight: 200,
                                                                                                                                                                                                                                                                                        letterSpacing: '-0.02em',
                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                Refalight
                                                                                                                                                                                                                                                                                                                                            </h2>

                                                                                                                                                                                                                                                                                                                                                        <div className="h-px w-16 bg-[#38BDF8] mb-8" />
                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                            <div className="section-reveal stagger-1 space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                        <p
                                                                                                                                                                                                                                                                                                                                                                                                      className="text-white text-xl font-light"
                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ fontFamily: 'Noto Sans JP, sans-serif' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                              リファライト
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-[#94A3B8] font-light leading-[1.9] text-[15px]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Refalight（リファライト）は、日本の音楽アーティスト。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-[#94A3B8] font-light leading-[1.9] text-[15px]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          日々の中で感じる光や感情を音楽に変え、
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        新しい景色を描いていく。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-[#94A3B8] font-light leading-[1.9] text-[15px]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              The next chapter starts here.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }