const platforms = [
      {
          name: 'Spotify',
              url: 'https://open.spotify.com/artist/1anE2wxPgnQdKn1memzJ1k',
                },
                  {
                      name: 'Apple Music',
                          url: 'https://music.apple.com/us/album/%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88%E3%83%A9%E3%82%A4%E3%83%B3-single/1888731652',
                            },
                              {
                                  name: 'YouTube Music',
                                      url: 'https://music.youtube.com/watch?v=4vLtyUZVM00',
                                        },
                                          {
                                              name: 'Amazon Music',
                                                  url: 'https://music.amazon.co.jp/albums/B0GV5M94CG?trackAsin=B0GV5PKG22',
                                                    },
                                                    ];

                                                    export default function Music() {
                                                      return (
                                                          <section id="music" className="py-24 px-6">
                                                                <div className="mx-auto max-w-5xl">
                                                                        <p className="mb-3 text-sm tracking-[0.3em] opacity-60">
                                                                                  LATEST RELEASE
                                                                                          </p>

                                                                                                  <h2 className="text-4xl font-light md:text-5xl">Music</h2>

                                                                                                          <div className="mt-12 grid gap-10 md:grid-cols-2 md:items-center">
                                                                                                                    <div className="aspect-square rounded-2xl bg-gradient-to-br from-sky-400/40 via-blue-700/30 to-slate-950 flex items-center justify-center">
                                                                                                                                <div className="text-center">
                                                                                                                                              <p className="text-sm tracking-[0.3em] opacity-70">REFALIGHT</p>
                                                                                                                                                            <h3 className="mt-4 text-3xl font-light">スタートライン</h3>
                                                                                                                                                                          <p className="mt-3 text-sm opacity-60">First Single</p>
                                                                                                                                                                                      </div>
                                                                                                                                                                                                </div>

                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                      <p className="text-sm tracking-[0.25em] opacity-60">
                                                                                                                                                                                                                                    FIRST SINGLE
                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                            <h3 className="mt-3 text-3xl font-light">スタートライン</h3>

                                                                                                                                                                                                                                                                        <p className="mt-6 leading-8 opacity-70">
                                                                                                                                                                                                                                                                                      Refalight first single.
                                                                                                                                                                                                                                                                                                    <br />
                                                                                                                                                                                                                                                                                                                  ここから始まる、新しい音楽の旅。
                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                          <div className="mt-8 flex flex-wrap gap-3">
                                                                                                                                                                                                                                                                                                                                                        {platforms.map((platform) => (
                                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                                          key={platform.name}
                                                                                                                                                                                                                                                                                                                                                                                                            href={platform.url}
                                                                                                                                                                                                                                                                                                                                                                                                                              target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="rounded-full border border-white/20 px-5 py-3 text-sm hover:bg-white/10"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {platform.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
